use faz_solidaria;

insert into categoria (tipo_alimento) values ('Frutas');
insert into categoria (tipo_alimento) values ('Verduras');
insert into categoria (tipo_alimento) values ('Legumes');

insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('A maçã possui um excelente valor nutritivo pois, em sua casca encontramos a pectina, que ajuda a reduzir o colesterol do sangue. Além disso, é um fruto rico em vitaminas B1, B2, niacina, ferro e fósforo. Aproximadamente 280g.', 50, 'https://i.imgur.com/mXpZEXy.png', 'Maçã Gala', 7.89, 1, 1);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('É a fruta mais popular do Brasil e um dos símbolos de países tropicais, a banana prata é também chamada de banana anã grande. Com alto valor nutritivo, é rica em açúcar e sais minerais, como potássio, e vitaminas A, B1, B2 e C.', 50, 'https://i.imgur.com/T0930zY.png', 'Banana Prata', 4.49, 1, 1);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('Por ser rica em Vitamina C e nas Vitaminas B2 e B5, a lima desintoxica o fígado, limpa o sistema linfático e elimina as toxinas do sangue. Aproximadamente 240g.', 50, 'https://i.imgur.com/u4DheyR.png', 'Laranja Lima', 7.82, 1, 1);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('O maracujá tem alto teor em vitamina C, ótimo antioxidante, e contém vitamina A e o potássio, que equilibra o nível de sódio e evita a pressão alta e doenças vasculares cerebrais. Aproximadamente 400g', 50, 'https://i.imgur.com/TqvqmbL.png', 'Maracujá', 11.90, 1, 1);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('A mexerica é uma fruta cítrica rica em fibras, vitamina C e potássio. Ótima na prevenção a doenças cardiovasculares, arteriosclerose e AVC. Aproximadamente 250g.', 50, 'https://i.imgur.com/oEtkBLs.png', 'Tangerina', 8.99, 1, 1);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('Morango são naturalmente baixos em calorias e em sódio e açúcar. A coloração vermelha contém antocianinas, que estimulam a queima de gordura armazenada. ', 50, 'https://i.imgur.com/1NoALkX.png', 'Morango', 7.99, 1, 1);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('As uvas verdes são frutas ricas em potássio, vitamina A, ácidos orgânicos e compostos fenólicos. ', 50, 'https://i.imgur.com/AtMmD3N.png', 'Uva Verde s/ Semente', 17.99, 1, 1);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('O limão tahiti contém vitamina B1, B2 e B3, provitamina A (caroteno), que se encontra principalmente na casca e, vitamina A na polpa fresca e sumo. Aproximadamente 100g.', 50, 'https://i.imgur.com/5UDAzdQ.png', 'Limão Tahiti', 7.99, 1, 1);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('A Carambola é rica em potássio, com 200 mg/100 g; cálcio, com 4 a 9 mg/100 g, e ferro, 0,8 a 2 mg, contendo ainda sódio e fósforo. ', 50, 'https://i.imgur.com/0NYSCux.png', 'Carambola', 9.99, 1, 1);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('O melão é rico em vitaminas A, B e C. Também é um excelente hidrante, pois contém aproximadamente 90% de água, que auxilia no funcionamento do intestino, aumenta o efeito diurético e elimina as toxinas no organismo.', 50, 'https://i.imgur.com/Qq6V9Fq.png', 'Melão Amarelo', 8.99, 1, 1);

insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('O Agrião é uma verdura rica em vitamina C, Vitamina A e flavonoides, compostos com propriedades e antioxidantes anti-inflamatórias que combatem os radicais livres e fortalecem o sistema imunológico.', 50, 'https://i.imgur.com/EpUqAw1.png', 'Agrião', 2.99, 1, 2);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('Essa alface é uma ótima fonte de carotenoides, pigmentos com propriedades antioxidantes que protegem o corpo da ação degenerativa dos radicais livres.', 50, 'https://i.imgur.com/KYxMB4c.png', 'Alface Lisa', 4.27, 1, 2);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('O Brócolis é bastante nutritivo, sendo uma boa fonte de fibras e proteínas, além de ter ferro, potássio, cálcio e magnésio. E também possui vitaminas A, C, E e K.', 50, 'https://i.imgur.com/jiTlfk2.png', 'Brócolis', 11.99, 1, 2);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('A couve-manteiga é rica em fibras, é fonte de ferro, cálcio, vitaminas A, C, k e ácido fólico. E também possui antioxidantes importantes que ajudam a prevenir doenças. Além disso, contém poucas calorias e é recomendada para quem quer controlar o peso.', 50, 'https://i.imgur.com/IxRYmrr.png', 'Couve Manteiga', 4.95, 1, 2);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('A couve-flor contém antioxidantes e é fonte de potássio, fósforo, cálcio, manganês, vitaminas do complexo B, além de K e C.', 50, 'https://i.imgur.com/5SL4VVW.png', 'Couve Flor', 12.99, 1, 2);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('A primeira coisa que você precisa saber a respeito da hortelã é que ela é rica em vitaminas A, C, D e do complexo B. Melhora a digestão, Alivia a síndrome do intestino irritado, Melhora a saúde bucal. Dentre outros.', 50, 'https://i.imgur.com/G01lgOg.png', 'Hortelã', 2.99, 1, 2);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('A Erva Doce é extremamente aromática e utilizada a centenas de anos no combate a problemas de acidez estomacal, cólica e dores de barriga.', 50, 'https://i.imgur.com/1jjFm6s.png', 'Erva Doce', 3.49, 1, 2);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('O louro também pode ser utilizado no tratamento de problemas digestivos, infecções, estresse e ansiedade, por exemplo, devido às suas propriedades', 50, 'https://i.imgur.com/g3kXv3M.png', 'Folha de Louro', 2.99, 1, 2);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('Rico em fibras, auxilia no processo digestivo, é diurético, ajuda eliminar as toxinas do organismo e tem baixa caloria', 50, 'https://i.imgur.com/uv4OZPs.png', 'Alho Poró', 8.99, 1, 2);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('A salsa é rica em vitaminas A, K e B além de minerais como o magnésio.', 50, 'https://i.imgur.com/gJDvYUR.png', 'Salsa', 4.99, 1, 2);



insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('A abóbora japonesa é um alimento rico em fibras, vitaminas e diversos nutrientes. Dentre suas propriedades mais conhecidas, podemos citar a alta concentração de betacaroteno. Esse composto pode ser convertido em vitamina A pelo corpo.', 50, 'https://i.imgur.com/xx0tNYX.png', 'Abóbora Japonesa', 9.90, 1, 3);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('A batata doce é um tubérculo, ou raiz, que tem ótima quantidade de energia, pois tem alto teor de carboidratos e ainda é rica em fibras, vitaminas do complexo B, vitamina A, vitamina C e minerais.', 50, 'https://i.imgur.com/ELBYecL.png', 'Batata Doce', 3.98, 1, 3);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('Por ser rica em potássio e ter fibras, a mandioca também é um alimento benéfico para o coração. O potássio regula os fluídos e ajuda a aliviar a tensão nos vasos sanguíneos e artérias.', 50, 'https://i.imgur.com/4CY7rij.png', 'Mandioca', 4.99, 1, 3);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('Essa raiz tuberosa é rica em vitaminas A, B1, B2, C, D e E, além de carboidratos, potássio, silício, fósforo, enxofre, cloro, cálcio, ferro e magnésio.', 50, 'https://i.imgur.com/ijvjcN0.png', 'Mandioquinha', 14.90, 1, 3);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('Essa raiz tuberosa é rica em vitaminas A, B1, B2, C, D e E, além de carboidratos, potássio, silício, fósforo, enxofre, cloro, cálcio, ferro e magnésio.', 50, 'https://i.imgur.com/5cBwmzs.png', 'Inhame', 3.49, 1, 3);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('Gengibre, ele é fonte de minerais, incluindo magnésio, cálcio e potássio. Além disso, possui vitamina C e B6, Reduz cólicas menstruais, Ajuda a emagrecer, Melhora a memória. Dentre outros.', 50, 'https://i.imgur.com/GBzAKA5.png', 'Gengibre', 12.99, 1, 3);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('A Cebola possui propriedades antivirais, antifúngicas, antibacterianas, anti-inflamatórias, anticancerígenas e hipoglicemiantes.', 50, 'https://i.imgur.com/zHAnBHP.png', 'Cebola', 5.99, 1, 3);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('A Cenoura possui quantidades expressivas de Vitamina A, antioxidantes e Betacaroteno, que estão associados ao melhor funcionamento dos receptores da retina e ao retardo do envelhecimento.', 50, 'https://i.imgur.com/07ClX35.png', 'Cenoura', 7.99, 1, 3);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('O Milho é um alimento super nutritivo especialmente por conta da alta quantidade de aminoácidos que o compõem e por conter fibras e vitaminas B1, B2 e E.', 50, 'https://i.imgur.com/gP7zbxT.png', 'Milho Verde', 8.99, 1, 3);
insert into produto (descricao, estoque, imagem, nome, preco, qtd, categoria_id) values ('Rabanete possui poucas calorias, mas fornece uma série de nutrientes, como potássio, cálcio, magnésio, fósforo, cobre e zinco. Além disso, o rabanete também contém fibras, que dão a sensação de saciedade e ajudam a controlar o apetite.', 50, 'https://i.imgur.com/w8kNHme.png', 'Rabanete', 3.49, 1, 3);